### ISSUE TITLE
Colab weirdness

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/aerial-segmentation#16]
## Problem

I am unable to open the colab once its pr has been merged to main.

## Solution

re-save colab? And / or provide a link to the colab.

**Comment by hlydecker** [comment]
This link should work:

https://colab.research.google.com/github/Sydney-Informatics-Hub/aerial-segmentation/blob/main/notebooks/detectron2_fine_tuning_colab.ipynb

Maybe add into the readme of the notebooks folder?

**Comment by mauch** [comment]
Aha. Will do!

**Comment by mauch** [comment]
Solved by #18

**Comment by hlydecker** [comment]
FYI: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
